import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsDbInstanceResourceSchema = resource("aws_db_instance", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    address: attr.string().computed(),
    allocated_storage: attr.number().optional().computed(),
    allow_major_version_upgrade: attr.bool().optional(),
    apply_immediately: attr.bool().optional(),
    arn: attr.string().computed(),
    auto_minor_version_upgrade: attr.bool().optional(),
    availability_zone: attr.string().optional().computed(),
    backup_retention_period: attr.number().optional().computed(),
    backup_target: attr.string().optional().computed(),
    backup_window: attr.string().optional().computed(),
    ca_cert_identifier: attr.string().optional().computed(),
    character_set_name: attr.string().optional().computed(),
    copy_tags_to_snapshot: attr.bool().optional(),
    custom_iam_instance_profile: attr.string().optional(),
    customer_owned_ip_enabled: attr.bool().optional(),
    database_insights_mode: attr.string().optional().computed(),
    db_name: attr.string().optional().computed(),
    db_subnet_group_name: attr.string().optional().computed(),
    dedicated_log_volume: attr.bool().optional(),
    delete_automated_backups: attr.bool().optional(),
    deletion_protection: attr.bool().optional(),
    domain: attr.string().optional(),
    domain_auth_secret_arn: attr.string().optional(),
    domain_dns_ips: attr.list().optional(),
    domain_fqdn: attr.string().optional().computed(),
    domain_iam_role_name: attr.string().optional(),
    domain_ou: attr.string().optional(),
    enabled_cloudwatch_logs_exports: attr.set().optional(),
    endpoint: attr.string().computed(),
    engine: attr.string().optional().computed(),
    engine_lifecycle_support: attr.string().optional().computed(),
    engine_version: attr.string().optional().computed(),
    engine_version_actual: attr.string().computed(),
    final_snapshot_identifier: attr.string().optional(),
    hosted_zone_id: attr.string().computed(),
    iam_database_authentication_enabled: attr.bool().optional(),
    id: attr.string().optional().computed(),
    identifier: attr.string().optional().computed(),
    identifier_prefix: attr.string().optional().computed(),
    instance_class: attr.string().required(),
    iops: attr.number().optional().computed(),
    kms_key_id: attr.string().optional().computed(),
    latest_restorable_time: attr.string().computed(),
    license_model: attr.string().optional().computed(),
    maintenance_window: attr.string().optional().computed(),
    manage_master_user_password: attr.bool().optional(),
    master_user_secret_kms_key_id: attr.string().optional().computed(),
    max_allocated_storage: attr.number().optional(),
    monitoring_interval: attr.number().optional(),
    monitoring_role_arn: attr.string().optional().computed(),
    multi_az: attr.bool().optional().computed(),
    nchar_character_set_name: attr.string().optional().computed(),
    network_type: attr.string().optional().computed(),
    option_group_name: attr.string().optional().computed(),
    parameter_group_name: attr.string().optional().computed(),
    password: attr.string().optional().sensitive(),
    password_wo: attr.string().optional().sensitive(),
    password_wo_version: attr.number().optional(),
    performance_insights_enabled: attr.bool().optional(),
    performance_insights_kms_key_id: attr.string().optional().computed(),
    performance_insights_retention_period: attr.number().optional().computed(),
    port: attr.number().optional().computed(),
    publicly_accessible: attr.bool().optional(),
    region: attr.string().optional().computed(),
    replica_mode: attr.string().optional().computed(),
    replicas: attr.list().computed(),
    replicate_source_db: attr.string().optional(),
    resource_id: attr.string().computed(),
    skip_final_snapshot: attr.bool().optional(),
    snapshot_identifier: attr.string().optional().computed(),
    status: attr.string().computed(),
    storage_encrypted: attr.bool().optional(),
    storage_throughput: attr.number().optional().computed(),
    storage_type: attr.string().optional().computed(),
    tags: attr.map().optional(),
    tags_all: attr.map().optional().computed(),
    timezone: attr.string().optional().computed(),
    upgrade_rollout_order: attr.string().computed(),
    upgrade_storage_config: attr.bool().optional(),
    username: attr.string().optional().computed(),
    vpc_security_group_ids: attr.set().optional().computed(),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    blue_green_update: block.single(
      {
        attributes: {
          enabled: attr.bool().optional(),
        },
      },
      { maxItems: 1 },
    ),
    listener_endpoint: block.list({
      attributes: {
        address: attr.string().optional(),
        hosted_zone_id: attr.string().optional(),
        port: attr.number().optional(),
      },
    }),
    master_user_secret: block.list({
      attributes: {
        kms_key_id: attr.string().optional(),
        secret_arn: attr.string().optional(),
        secret_status: attr.string().optional(),
      },
    }),
    restore_to_point_in_time: block.single(
      {
        attributes: {
          restore_time: attr.string().optional(),
          source_db_instance_automated_backups_arn: attr.string().optional(),
          source_db_instance_identifier: attr.string().optional(),
          source_dbi_resource_id: attr.string().optional(),
          use_latest_restorable_time: attr.bool().optional(),
        },
      },
      { maxItems: 1 },
    ),
    s3_import: block.single(
      {
        attributes: {
          bucket_name: attr.string().required(),
          bucket_prefix: attr.string().optional(),
          ingestion_role: attr.string().required(),
          source_engine: attr.string().required(),
          source_engine_version: attr.string().required(),
        },
      },
      { maxItems: 1 },
    ),
    timeouts: block.single({
      attributes: {
        create: attr.string().optional(),
        delete: attr.string().optional(),
        update: attr.string().optional(),
      },
    }),
  },
});
