import { resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsDbInstanceResourceSchema = resource("aws_db_instance", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    address: { valueType: "string", computed: true },
    allocated_storage: { valueType: "number", optional: true, computed: true },
    allow_major_version_upgrade: { valueType: "bool", optional: true },
    apply_immediately: { valueType: "bool", optional: true },
    arn: { valueType: "string", computed: true },
    auto_minor_version_upgrade: { valueType: "bool", optional: true },
    availability_zone: { valueType: "string", optional: true, computed: true },
    backup_retention_period: {
      valueType: "number",
      optional: true,
      computed: true,
    },
    backup_target: { valueType: "string", optional: true, computed: true },
    backup_window: { valueType: "string", optional: true, computed: true },
    ca_cert_identifier: { valueType: "string", optional: true, computed: true },
    character_set_name: { valueType: "string", optional: true, computed: true },
    copy_tags_to_snapshot: { valueType: "bool", optional: true },
    custom_iam_instance_profile: { valueType: "string", optional: true },
    customer_owned_ip_enabled: { valueType: "bool", optional: true },
    database_insights_mode: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    db_name: { valueType: "string", optional: true, computed: true },
    db_subnet_group_name: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    dedicated_log_volume: { valueType: "bool", optional: true },
    delete_automated_backups: { valueType: "bool", optional: true },
    deletion_protection: { valueType: "bool", optional: true },
    domain: { valueType: "string", optional: true },
    domain_auth_secret_arn: { valueType: "string", optional: true },
    domain_dns_ips: { valueType: "list", optional: true },
    domain_fqdn: { valueType: "string", optional: true, computed: true },
    domain_iam_role_name: { valueType: "string", optional: true },
    domain_ou: { valueType: "string", optional: true },
    enabled_cloudwatch_logs_exports: { valueType: "set", optional: true },
    endpoint: { valueType: "string", computed: true },
    engine: { valueType: "string", optional: true, computed: true },
    engine_lifecycle_support: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    engine_version: { valueType: "string", optional: true, computed: true },
    engine_version_actual: { valueType: "string", computed: true },
    final_snapshot_identifier: { valueType: "string", optional: true },
    hosted_zone_id: { valueType: "string", computed: true },
    iam_database_authentication_enabled: { valueType: "bool", optional: true },
    id: { valueType: "string", optional: true, computed: true },
    identifier: { valueType: "string", optional: true, computed: true },
    identifier_prefix: { valueType: "string", optional: true, computed: true },
    instance_class: { valueType: "string", required: true },
    iops: { valueType: "number", optional: true, computed: true },
    kms_key_id: { valueType: "string", optional: true, computed: true },
    latest_restorable_time: { valueType: "string", computed: true },
    license_model: { valueType: "string", optional: true, computed: true },
    maintenance_window: { valueType: "string", optional: true, computed: true },
    manage_master_user_password: { valueType: "bool", optional: true },
    master_user_secret_kms_key_id: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    max_allocated_storage: { valueType: "number", optional: true },
    monitoring_interval: { valueType: "number", optional: true },
    monitoring_role_arn: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    multi_az: { valueType: "bool", optional: true, computed: true },
    nchar_character_set_name: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    network_type: { valueType: "string", optional: true, computed: true },
    option_group_name: { valueType: "string", optional: true, computed: true },
    parameter_group_name: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    password: { valueType: "string", optional: true, sensitive: true },
    password_wo: { valueType: "string", optional: true, sensitive: true },
    password_wo_version: { valueType: "number", optional: true },
    performance_insights_enabled: { valueType: "bool", optional: true },
    performance_insights_kms_key_id: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    performance_insights_retention_period: {
      valueType: "number",
      optional: true,
      computed: true,
    },
    port: { valueType: "number", optional: true, computed: true },
    publicly_accessible: { valueType: "bool", optional: true },
    region: { valueType: "string", optional: true, computed: true },
    replica_mode: { valueType: "string", optional: true, computed: true },
    replicas: { valueType: "list", computed: true },
    replicate_source_db: { valueType: "string", optional: true },
    resource_id: { valueType: "string", computed: true },
    skip_final_snapshot: { valueType: "bool", optional: true },
    snapshot_identifier: {
      valueType: "string",
      optional: true,
      computed: true,
    },
    status: { valueType: "string", computed: true },
    storage_encrypted: { valueType: "bool", optional: true },
    storage_throughput: { valueType: "number", optional: true, computed: true },
    storage_type: { valueType: "string", optional: true, computed: true },
    tags: { valueType: "map", optional: true },
    tags_all: { valueType: "map", optional: true, computed: true },
    timezone: { valueType: "string", optional: true, computed: true },
    upgrade_rollout_order: { valueType: "string", computed: true },
    upgrade_storage_config: { valueType: "bool", optional: true },
    username: { valueType: "string", optional: true, computed: true },
    vpc_security_group_ids: {
      valueType: "set",
      optional: true,
      computed: true,
    },
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    blue_green_update: {
      nestingMode: "single",
      maxItems: 1,
      attributes: {
        enabled: { valueType: "bool", optional: true },
      },
    },
    listener_endpoint: {
      nestingMode: "list",
      attributes: {
        address: { valueType: "string", optional: true },
        hosted_zone_id: { valueType: "string", optional: true },
        port: { valueType: "number", optional: true },
      },
    },
    master_user_secret: {
      nestingMode: "list",
      attributes: {
        kms_key_id: { valueType: "string", optional: true },
        secret_arn: { valueType: "string", optional: true },
        secret_status: { valueType: "string", optional: true },
      },
    },
    restore_to_point_in_time: {
      nestingMode: "single",
      maxItems: 1,
      attributes: {
        restore_time: { valueType: "string", optional: true },
        source_db_instance_automated_backups_arn: {
          valueType: "string",
          optional: true,
        },
        source_db_instance_identifier: { valueType: "string", optional: true },
        source_dbi_resource_id: { valueType: "string", optional: true },
        use_latest_restorable_time: { valueType: "bool", optional: true },
      },
    },
    s3_import: {
      nestingMode: "single",
      maxItems: 1,
      attributes: {
        bucket_name: { valueType: "string", required: true },
        bucket_prefix: { valueType: "string", optional: true },
        ingestion_role: { valueType: "string", required: true },
        source_engine: { valueType: "string", required: true },
        source_engine_version: { valueType: "string", required: true },
      },
    },
    timeouts: {
      nestingMode: "single",
      attributes: {
        create: { valueType: "string", optional: true },
        delete: { valueType: "string", optional: true },
        update: { valueType: "string", optional: true },
      },
    },
  },
});
