// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsVpcResourceSchema = resource("aws_vpc", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    arn: attr.string({ computed: true }),
    assign_generated_ipv6_cidr_block: attr.bool({ optional: true }),
    cidr_block: attr.string({ optional: true, computed: true }),
    default_network_acl_id: attr.string({ computed: true }),
    default_route_table_id: attr.string({ computed: true }),
    default_security_group_id: attr.string({ computed: true }),
    dhcp_options_id: attr.string({ computed: true }),
    enable_dns_hostnames: attr.bool({ optional: true, computed: true }),
    enable_dns_support: attr.bool({ optional: true }),
    enable_network_address_usage_metrics: attr.bool({
      optional: true,
      computed: true,
    }),
    id: attr.string({ optional: true, computed: true }),
    instance_tenancy: attr.string({ optional: true }),
    ipv4_ipam_pool_id: attr.string({ optional: true }),
    ipv4_netmask_length: attr.number({ optional: true }),
    ipv6_association_id: attr.string({ computed: true }),
    ipv6_cidr_block: attr.string({ optional: true, computed: true }),
    ipv6_cidr_block_network_border_group: attr.string({
      optional: true,
      computed: true,
    }),
    ipv6_ipam_pool_id: attr.string({ optional: true }),
    ipv6_netmask_length: attr.number({ optional: true }),
    main_route_table_id: attr.string({ computed: true }),
    owner_id: attr.string({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
  },
});
