import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsDbInstanceResourceSchema = resource("aws_db_instance", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    address: attr.string({ computed: true }),
    allocated_storage: attr.number({ optional: true, computed: true }),
    allow_major_version_upgrade: attr.bool({ optional: true }),
    apply_immediately: attr.bool({ optional: true }),
    arn: attr.string({ computed: true }),
    auto_minor_version_upgrade: attr.bool({ optional: true }),
    availability_zone: attr.string({ optional: true, computed: true }),
    backup_retention_period: attr.number({ optional: true, computed: true }),
    backup_target: attr.string({ optional: true, computed: true }),
    backup_window: attr.string({ optional: true, computed: true }),
    ca_cert_identifier: attr.string({ optional: true, computed: true }),
    character_set_name: attr.string({ optional: true, computed: true }),
    copy_tags_to_snapshot: attr.bool({ optional: true }),
    custom_iam_instance_profile: attr.string({ optional: true }),
    customer_owned_ip_enabled: attr.bool({ optional: true }),
    database_insights_mode: attr.string({ optional: true, computed: true }),
    db_name: attr.string({ optional: true, computed: true }),
    db_subnet_group_name: attr.string({ optional: true, computed: true }),
    dedicated_log_volume: attr.bool({ optional: true }),
    delete_automated_backups: attr.bool({ optional: true }),
    deletion_protection: attr.bool({ optional: true }),
    domain: attr.string({ optional: true }),
    domain_auth_secret_arn: attr.string({ optional: true }),
    domain_dns_ips: attr.list({ optional: true }),
    domain_fqdn: attr.string({ optional: true, computed: true }),
    domain_iam_role_name: attr.string({ optional: true }),
    domain_ou: attr.string({ optional: true }),
    enabled_cloudwatch_logs_exports: attr.set({ optional: true }),
    endpoint: attr.string({ computed: true }),
    engine: attr.string({ optional: true, computed: true }),
    engine_lifecycle_support: attr.string({ optional: true, computed: true }),
    engine_version: attr.string({ optional: true, computed: true }),
    engine_version_actual: attr.string({ computed: true }),
    final_snapshot_identifier: attr.string({ optional: true }),
    hosted_zone_id: attr.string({ computed: true }),
    iam_database_authentication_enabled: attr.bool({ optional: true }),
    id: attr.string({ optional: true, computed: true }),
    identifier: attr.string({ optional: true, computed: true }),
    identifier_prefix: attr.string({ optional: true, computed: true }),
    instance_class: attr.string({ required: true }),
    iops: attr.number({ optional: true, computed: true }),
    kms_key_id: attr.string({ optional: true, computed: true }),
    latest_restorable_time: attr.string({ computed: true }),
    license_model: attr.string({ optional: true, computed: true }),
    maintenance_window: attr.string({ optional: true, computed: true }),
    manage_master_user_password: attr.bool({ optional: true }),
    master_user_secret_kms_key_id: attr.string({
      optional: true,
      computed: true,
    }),
    max_allocated_storage: attr.number({ optional: true }),
    monitoring_interval: attr.number({ optional: true }),
    monitoring_role_arn: attr.string({ optional: true, computed: true }),
    multi_az: attr.bool({ optional: true, computed: true }),
    nchar_character_set_name: attr.string({ optional: true, computed: true }),
    network_type: attr.string({ optional: true, computed: true }),
    option_group_name: attr.string({ optional: true, computed: true }),
    parameter_group_name: attr.string({ optional: true, computed: true }),
    password: attr.string({ optional: true, sensitive: true }),
    password_wo: attr.string({ optional: true, sensitive: true }),
    password_wo_version: attr.number({ optional: true }),
    performance_insights_enabled: attr.bool({ optional: true }),
    performance_insights_kms_key_id: attr.string({
      optional: true,
      computed: true,
    }),
    performance_insights_retention_period: attr.number({
      optional: true,
      computed: true,
    }),
    port: attr.number({ optional: true, computed: true }),
    publicly_accessible: attr.bool({ optional: true }),
    region: attr.string({ optional: true, computed: true }),
    replica_mode: attr.string({ optional: true, computed: true }),
    replicas: attr.list({ computed: true }),
    replicate_source_db: attr.string({ optional: true }),
    resource_id: attr.string({ computed: true }),
    skip_final_snapshot: attr.bool({ optional: true }),
    snapshot_identifier: attr.string({ optional: true, computed: true }),
    status: attr.string({ computed: true }),
    storage_encrypted: attr.bool({ optional: true }),
    storage_throughput: attr.number({ optional: true, computed: true }),
    storage_type: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
    timezone: attr.string({ optional: true, computed: true }),
    upgrade_rollout_order: attr.string({ computed: true }),
    upgrade_storage_config: attr.bool({ optional: true }),
    username: attr.string({ optional: true, computed: true }),
    vpc_security_group_ids: attr.set({ optional: true, computed: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    blue_green_update: block.single(
      {
        attributes: {
          enabled: attr.bool({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    listener_endpoint: block.list({
      attributes: {
        address: attr.string({ optional: true }),
        hosted_zone_id: attr.string({ optional: true }),
        port: attr.number({ optional: true }),
      },
    }),
    master_user_secret: block.list({
      attributes: {
        kms_key_id: attr.string({ optional: true }),
        secret_arn: attr.string({ optional: true }),
        secret_status: attr.string({ optional: true }),
      },
    }),
    restore_to_point_in_time: block.single(
      {
        attributes: {
          restore_time: attr.string({ optional: true }),
          source_db_instance_automated_backups_arn: attr.string({
            optional: true,
          }),
          source_db_instance_identifier: attr.string({ optional: true }),
          source_dbi_resource_id: attr.string({ optional: true }),
          use_latest_restorable_time: attr.bool({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    s3_import: block.single(
      {
        attributes: {
          bucket_name: attr.string({ required: true }),
          bucket_prefix: attr.string({ optional: true }),
          ingestion_role: attr.string({ required: true }),
          source_engine: attr.string({ required: true }),
          source_engine_version: attr.string({ required: true }),
        },
      },
      { maxItems: 1 },
    ),
    timeouts: block.single({
      attributes: {
        create: attr.string({ optional: true }),
        delete: attr.string({ optional: true }),
        update: attr.string({ optional: true }),
      },
    }),
  },
});
