// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsAutoscalingGroupResourceSchema = resource(
  "aws_autoscaling_group",
  {
    attributes: {
      ...COMMON_RESOURCE_ATTRIBUTES,
      arn: attr.string({ computed: true }),
      availability_zones: attr.set({ optional: true, computed: true }),
      capacity_rebalance: attr.bool({ optional: true }),
      context: attr.string({ optional: true }),
      default_cooldown: attr.number({ optional: true, computed: true }),
      default_instance_warmup: attr.number({ optional: true }),
      desired_capacity: attr.number({ optional: true, computed: true }),
      desired_capacity_type: attr.string({ optional: true }),
      enabled_metrics: attr.set({ optional: true }),
      force_delete: attr.bool({ optional: true }),
      force_delete_warm_pool: attr.bool({ optional: true }),
      health_check_grace_period: attr.number({ optional: true }),
      health_check_type: attr.string({ optional: true, computed: true }),
      id: attr.string({ optional: true, computed: true }),
      ignore_failed_scaling_activities: attr.bool({ optional: true }),
      launch_configuration: attr.string({ optional: true }),
      load_balancers: attr.set({ optional: true, computed: true }),
      max_instance_lifetime: attr.number({ optional: true }),
      max_size: attr.number({ required: true }),
      metrics_granularity: attr.string({ optional: true }),
      min_elb_capacity: attr.number({ optional: true }),
      min_size: attr.number({ required: true }),
      name: attr.string({ optional: true, computed: true }),
      name_prefix: attr.string({ optional: true, computed: true }),
      placement_group: attr.string({ optional: true }),
      predicted_capacity: attr.number({ computed: true }),
      protect_from_scale_in: attr.bool({ optional: true }),
      region: attr.string({ optional: true, computed: true }),
      service_linked_role_arn: attr.string({ optional: true, computed: true }),
      suspended_processes: attr.set({ optional: true }),
      target_group_arns: attr.set({ optional: true, computed: true }),
      termination_policies: attr.list({ optional: true }),
      vpc_zone_identifier: attr.set({ optional: true, computed: true }),
      wait_for_capacity_timeout: attr.string({ optional: true }),
      wait_for_elb_capacity: attr.number({ optional: true }),
      warm_pool_size: attr.number({ computed: true }),
    },
    blocks: {
      ...COMMON_RESOURCE_BLOCKS,
      availability_zone_distribution: block.single(
        {
          attributes: {
            capacity_distribution_strategy: attr.string({ optional: true }),
          },
        },
        { maxItems: 1 },
      ),
      capacity_reservation_specification: block.single(
        {
          attributes: {
            capacity_reservation_preference: attr.string({
              optional: true,
              computed: true,
            }),
          },
          blocks: {
            capacity_reservation_target: block.single(
              {
                attributes: {
                  capacity_reservation_ids: attr.list({ optional: true }),
                  capacity_reservation_resource_group_arns: attr.list({
                    optional: true,
                  }),
                },
              },
              { maxItems: 1 },
            ),
          },
        },
        { maxItems: 1 },
      ),
      initial_lifecycle_hook: block.set({
        attributes: {
          default_result: attr.string({ optional: true, computed: true }),
          heartbeat_timeout: attr.number({ optional: true }),
          lifecycle_transition: attr.string({ required: true }),
          name: attr.string({ required: true }),
          notification_metadata: attr.string({ optional: true }),
          notification_target_arn: attr.string({ optional: true }),
          role_arn: attr.string({ optional: true }),
        },
      }),
      instance_maintenance_policy: block.single(
        {
          attributes: {
            max_healthy_percentage: attr.number({ required: true }),
            min_healthy_percentage: attr.number({ required: true }),
          },
        },
        { maxItems: 1 },
      ),
      instance_refresh: block.single(
        {
          attributes: {
            strategy: attr.string({ required: true }),
            triggers: attr.set({ optional: true }),
          },
          blocks: {
            preferences: block.single(
              {
                attributes: {
                  auto_rollback: attr.bool({ optional: true }),
                  checkpoint_delay: attr.string({ optional: true }),
                  checkpoint_percentages: attr.list({ optional: true }),
                  instance_warmup: attr.string({ optional: true }),
                  max_healthy_percentage: attr.number({ optional: true }),
                  min_healthy_percentage: attr.number({ optional: true }),
                  scale_in_protected_instances: attr.string({ optional: true }),
                  skip_matching: attr.bool({ optional: true }),
                  standby_instances: attr.string({ optional: true }),
                },
                blocks: {
                  alarm_specification: block.single(
                    {
                      attributes: {
                        alarms: attr.list({ optional: true }),
                      },
                    },
                    { maxItems: 1 },
                  ),
                },
              },
              { maxItems: 1 },
            ),
          },
        },
        { maxItems: 1 },
      ),
      launch_template: block.single(
        {
          attributes: {
            id: attr.string({ optional: true, computed: true }),
            name: attr.string({ optional: true, computed: true }),
            version: attr.string({ optional: true, computed: true }),
          },
        },
        { maxItems: 1 },
      ),
      mixed_instances_policy: block.single(
        {
          attributes: {},
          blocks: {
            instances_distribution: block.single(
              {
                attributes: {
                  on_demand_allocation_strategy: attr.string({
                    optional: true,
                    computed: true,
                  }),
                  on_demand_base_capacity: attr.number({
                    optional: true,
                    computed: true,
                  }),
                  on_demand_percentage_above_base_capacity: attr.number({
                    optional: true,
                    computed: true,
                  }),
                  spot_allocation_strategy: attr.string({
                    optional: true,
                    computed: true,
                  }),
                  spot_instance_pools: attr.number({
                    optional: true,
                    computed: true,
                  }),
                  spot_max_price: attr.string({ optional: true }),
                },
              },
              { maxItems: 1 },
            ),
            launch_template: block.single(
              {
                attributes: {},
                blocks: {
                  launch_template_specification: block.single(
                    {
                      attributes: {
                        launch_template_id: attr.string({
                          optional: true,
                          computed: true,
                        }),
                        launch_template_name: attr.string({
                          optional: true,
                          computed: true,
                        }),
                        version: attr.string({
                          optional: true,
                          computed: true,
                        }),
                      },
                    },
                    { minItems: 1, maxItems: 1 },
                  ),
                  override: block.list({
                    attributes: {
                      instance_type: attr.string({ optional: true }),
                      weighted_capacity: attr.string({ optional: true }),
                    },
                    blocks: {
                      instance_requirements: block.single(
                        {
                          attributes: {
                            accelerator_manufacturers: attr.set({
                              optional: true,
                            }),
                            accelerator_names: attr.set({ optional: true }),
                            accelerator_types: attr.set({ optional: true }),
                            allowed_instance_types: attr.set({
                              optional: true,
                            }),
                            bare_metal: attr.string({ optional: true }),
                            burstable_performance: attr.string({
                              optional: true,
                            }),
                            cpu_manufacturers: attr.set({ optional: true }),
                            excluded_instance_types: attr.set({
                              optional: true,
                            }),
                            instance_generations: attr.set({ optional: true }),
                            local_storage: attr.string({ optional: true }),
                            local_storage_types: attr.set({ optional: true }),
                            max_spot_price_as_percentage_of_optimal_on_demand_price:
                              attr.number({ optional: true }),
                            on_demand_max_price_percentage_over_lowest_price:
                              attr.number({ optional: true }),
                            require_hibernate_support: attr.bool({
                              optional: true,
                            }),
                            spot_max_price_percentage_over_lowest_price:
                              attr.number({ optional: true }),
                          },
                          blocks: {
                            accelerator_count: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            accelerator_total_memory_mib: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            baseline_ebs_bandwidth_mbps: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            memory_gib_per_vcpu: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            memory_mib: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            network_bandwidth_gbps: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            network_interface_count: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            total_local_storage_gb: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                            vcpu_count: block.single(
                              {
                                attributes: {
                                  max: attr.number({ optional: true }),
                                  min: attr.number({ optional: true }),
                                },
                              },
                              { maxItems: 1 },
                            ),
                          },
                        },
                        { maxItems: 1 },
                      ),
                      launch_template_specification: block.single(
                        {
                          attributes: {
                            launch_template_id: attr.string({
                              optional: true,
                              computed: true,
                            }),
                            launch_template_name: attr.string({
                              optional: true,
                              computed: true,
                            }),
                            version: attr.string({
                              optional: true,
                              computed: true,
                            }),
                          },
                        },
                        { maxItems: 1 },
                      ),
                    },
                  }),
                },
              },
              { minItems: 1, maxItems: 1 },
            ),
          },
        },
        { maxItems: 1 },
      ),
      tag: block.set({
        attributes: {
          key: attr.string({ required: true }),
          propagate_at_launch: attr.bool({ required: true }),
          value: attr.string({ required: true }),
        },
      }),
      timeouts: block.single({
        attributes: {
          delete: attr.string({ optional: true }),
          update: attr.string({ optional: true }),
        },
      }),
      traffic_source: block.set({
        attributes: {
          identifier: attr.string({ required: true }),
          type: attr.string({ optional: true }),
        },
      }),
      warm_pool: block.single(
        {
          attributes: {
            max_group_prepared_capacity: attr.number({ optional: true }),
            min_size: attr.number({ optional: true }),
            pool_state: attr.string({ optional: true }),
          },
          blocks: {
            instance_reuse_policy: block.single(
              {
                attributes: {
                  reuse_on_scale_in: attr.bool({ optional: true }),
                },
              },
              { maxItems: 1 },
            ),
          },
        },
        { maxItems: 1 },
      ),
    },
  },
);
