// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsInstanceResourceSchema = resource("aws_instance", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    ami: attr.string({ optional: true, computed: true }),
    arn: attr.string({ computed: true }),
    associate_public_ip_address: attr.bool({ optional: true, computed: true }),
    availability_zone: attr.string({ optional: true, computed: true }),
    disable_api_stop: attr.bool({ optional: true, computed: true }),
    disable_api_termination: attr.bool({ optional: true, computed: true }),
    ebs_optimized: attr.bool({ optional: true, computed: true }),
    enable_primary_ipv6: attr.bool({ optional: true, computed: true }),
    force_destroy: attr.bool({ optional: true }),
    get_password_data: attr.bool({ optional: true }),
    hibernation: attr.bool({ optional: true }),
    host_id: attr.string({ optional: true, computed: true }),
    host_resource_group_arn: attr.string({ optional: true, computed: true }),
    iam_instance_profile: attr.string({ optional: true, computed: true }),
    id: attr.string({ optional: true, computed: true }),
    instance_initiated_shutdown_behavior: attr.string({
      optional: true,
      computed: true,
    }),
    instance_lifecycle: attr.string({ computed: true }),
    instance_state: attr.string({ computed: true }),
    instance_type: attr.string({ optional: true, computed: true }),
    ipv6_address_count: attr.number({ optional: true, computed: true }),
    ipv6_addresses: attr.list({ optional: true, computed: true }),
    key_name: attr.string({ optional: true, computed: true }),
    monitoring: attr.bool({ optional: true, computed: true }),
    outpost_arn: attr.string({ computed: true }),
    password_data: attr.string({ computed: true }),
    placement_group: attr.string({ optional: true, computed: true }),
    placement_group_id: attr.string({ optional: true, computed: true }),
    placement_partition_number: attr.number({ optional: true, computed: true }),
    primary_network_interface_id: attr.string({ computed: true }),
    private_dns: attr.string({ computed: true }),
    private_ip: attr.string({ optional: true, computed: true }),
    public_dns: attr.string({ computed: true }),
    public_ip: attr.string({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    secondary_private_ips: attr.set({ optional: true, computed: true }),
    security_groups: attr.set({ optional: true, computed: true }),
    source_dest_check: attr.bool({ optional: true }),
    spot_instance_request_id: attr.string({ computed: true }),
    subnet_id: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
    tenancy: attr.string({ optional: true, computed: true }),
    user_data: attr.string({ optional: true }),
    user_data_base64: attr.string({ optional: true, computed: true }),
    user_data_replace_on_change: attr.bool({ optional: true }),
    volume_tags: attr.map({ optional: true }),
    vpc_security_group_ids: attr.set({ optional: true, computed: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    capacity_reservation_specification: block.single(
      {
        attributes: {
          capacity_reservation_preference: attr.string({ optional: true }),
        },
        blocks: {
          capacity_reservation_target: block.single(
            {
              attributes: {
                capacity_reservation_id: attr.string({ optional: true }),
                capacity_reservation_resource_group_arn: attr.string({
                  optional: true,
                }),
              },
            },
            { maxItems: 1 },
          ),
        },
      },
      { maxItems: 1 },
    ),
    cpu_options: block.single(
      {
        attributes: {
          amd_sev_snp: attr.string({ optional: true, computed: true }),
          core_count: attr.number({ optional: true, computed: true }),
          threads_per_core: attr.number({ optional: true, computed: true }),
        },
      },
      { maxItems: 1 },
    ),
    credit_specification: block.single(
      {
        attributes: {
          cpu_credits: attr.string({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    ebs_block_device: block.set({
      attributes: {
        delete_on_termination: attr.bool({ optional: true }),
        device_name: attr.string({ required: true }),
        encrypted: attr.bool({ optional: true, computed: true }),
        iops: attr.number({ optional: true, computed: true }),
        kms_key_id: attr.string({ optional: true, computed: true }),
        snapshot_id: attr.string({ optional: true, computed: true }),
        tags: attr.map({ optional: true }),
        tags_all: attr.map({ optional: true, computed: true }),
        throughput: attr.number({ optional: true, computed: true }),
        volume_id: attr.string({ computed: true }),
        volume_size: attr.number({ optional: true, computed: true }),
        volume_type: attr.string({ optional: true, computed: true }),
      },
    }),
    enclave_options: block.single(
      {
        attributes: {
          enabled: attr.bool({ optional: true, computed: true }),
        },
      },
      { maxItems: 1 },
    ),
    ephemeral_block_device: block.set({
      attributes: {
        device_name: attr.string({ required: true }),
        no_device: attr.bool({ optional: true }),
        virtual_name: attr.string({ optional: true }),
      },
    }),
    instance_market_options: block.single(
      {
        attributes: {
          market_type: attr.string({ optional: true, computed: true }),
        },
        blocks: {
          spot_options: block.single(
            {
              attributes: {
                instance_interruption_behavior: attr.string({
                  optional: true,
                  computed: true,
                }),
                max_price: attr.string({ optional: true, computed: true }),
                spot_instance_type: attr.string({
                  optional: true,
                  computed: true,
                }),
                valid_until: attr.string({ optional: true, computed: true }),
              },
            },
            { maxItems: 1 },
          ),
        },
      },
      { maxItems: 1 },
    ),
    launch_template: block.single(
      {
        attributes: {
          id: attr.string({ optional: true, computed: true }),
          name: attr.string({ optional: true, computed: true }),
          version: attr.string({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    maintenance_options: block.single(
      {
        attributes: {
          auto_recovery: attr.string({ optional: true, computed: true }),
        },
      },
      { maxItems: 1 },
    ),
    metadata_options: block.single(
      {
        attributes: {
          http_endpoint: attr.string({ optional: true }),
          http_protocol_ipv6: attr.string({ optional: true }),
          http_put_response_hop_limit: attr.number({
            optional: true,
            computed: true,
          }),
          http_tokens: attr.string({ optional: true, computed: true }),
          instance_metadata_tags: attr.string({
            optional: true,
            computed: true,
          }),
        },
      },
      { maxItems: 1 },
    ),
    network_interface: block.set({
      attributes: {
        delete_on_termination: attr.bool({ optional: true }),
        device_index: attr.number({ required: true }),
        network_card_index: attr.number({ optional: true }),
        network_interface_id: attr.string({ required: true }),
      },
    }),
    primary_network_interface: block.single(
      {
        attributes: {
          delete_on_termination: attr.bool({ computed: true }),
          network_interface_id: attr.string({ required: true }),
        },
      },
      { maxItems: 1 },
    ),
    private_dns_name_options: block.single(
      {
        attributes: {
          enable_resource_name_dns_a_record: attr.bool({
            optional: true,
            computed: true,
          }),
          enable_resource_name_dns_aaaa_record: attr.bool({
            optional: true,
            computed: true,
          }),
          hostname_type: attr.string({ optional: true, computed: true }),
        },
      },
      { maxItems: 1 },
    ),
    root_block_device: block.single(
      {
        attributes: {
          delete_on_termination: attr.bool({ optional: true }),
          device_name: attr.string({ computed: true }),
          encrypted: attr.bool({ optional: true, computed: true }),
          iops: attr.number({ optional: true, computed: true }),
          kms_key_id: attr.string({ optional: true, computed: true }),
          tags: attr.map({ optional: true }),
          tags_all: attr.map({ optional: true, computed: true }),
          throughput: attr.number({ optional: true, computed: true }),
          volume_id: attr.string({ computed: true }),
          volume_size: attr.number({ optional: true, computed: true }),
          volume_type: attr.string({ optional: true, computed: true }),
        },
      },
      { maxItems: 1 },
    ),
    secondary_network_interface: block.set({
      attributes: {
        delete_on_termination: attr.bool({ optional: true }),
        device_index: attr.number({ optional: true }),
        interface_type: attr.string({ optional: true }),
        mac_address: attr.string({ computed: true }),
        network_card_index: attr.number({ required: true }),
        private_ip_address_count: attr.number({ optional: true }),
        private_ip_addresses: attr.list({ computed: true }),
        secondary_interface_id: attr.string({ computed: true }),
        secondary_network_id: attr.string({ computed: true }),
        secondary_subnet_id: attr.string({ required: true }),
        source_dest_check: attr.bool({ computed: true }),
        status: attr.string({ computed: true }),
      },
    }),
    timeouts: block.single({
      attributes: {
        create: attr.string({ optional: true }),
        delete: attr.string({ optional: true }),
        read: attr.string({ optional: true }),
        update: attr.string({ optional: true }),
      },
    }),
  },
});
