// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsSubnetResourceSchema = resource("aws_subnet", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    arn: attr.string({ computed: true }),
    assign_ipv6_address_on_creation: attr.bool({ optional: true }),
    availability_zone: attr.string({ optional: true, computed: true }),
    availability_zone_id: attr.string({ optional: true, computed: true }),
    cidr_block: attr.string({ optional: true, computed: true }),
    customer_owned_ipv4_pool: attr.string({ optional: true }),
    enable_dns64: attr.bool({ optional: true }),
    enable_lni_at_device_index: attr.number({ optional: true }),
    enable_resource_name_dns_a_record_on_launch: attr.bool({ optional: true }),
    enable_resource_name_dns_aaaa_record_on_launch: attr.bool({
      optional: true,
    }),
    id: attr.string({ optional: true, computed: true }),
    ipv4_ipam_pool_id: attr.string({ optional: true }),
    ipv4_netmask_length: attr.number({ optional: true }),
    ipv6_cidr_block: attr.string({ optional: true, computed: true }),
    ipv6_cidr_block_association_id: attr.string({ computed: true }),
    ipv6_ipam_pool_id: attr.string({ optional: true }),
    ipv6_native: attr.bool({ optional: true }),
    ipv6_netmask_length: attr.number({ optional: true }),
    map_customer_owned_ip_on_launch: attr.bool({ optional: true }),
    map_public_ip_on_launch: attr.bool({ optional: true }),
    outpost_arn: attr.string({ optional: true }),
    owner_id: attr.string({ computed: true }),
    private_dns_hostname_type_on_launch: attr.string({
      optional: true,
      computed: true,
    }),
    region: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
    vpc_id: attr.string({ required: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    timeouts: block.single({
      attributes: {
        create: attr.string({ optional: true }),
        delete: attr.string({ optional: true }),
      },
    }),
  },
});
