// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsS3BucketResourceSchema = resource("aws_s3_bucket", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    acceleration_status: attr.string({ optional: true, computed: true }),
    acl: attr.string({ optional: true, computed: true }),
    arn: attr.string({ computed: true }),
    bucket: attr.string({ optional: true, computed: true }),
    bucket_domain_name: attr.string({ computed: true }),
    bucket_prefix: attr.string({ optional: true, computed: true }),
    bucket_region: attr.string({ computed: true }),
    bucket_regional_domain_name: attr.string({ computed: true }),
    force_destroy: attr.bool({ optional: true }),
    hosted_zone_id: attr.string({ computed: true }),
    id: attr.string({ optional: true, computed: true }),
    object_lock_enabled: attr.bool({ optional: true, computed: true }),
    policy: attr.string({ optional: true, computed: true }),
    region: attr.string({ optional: true, computed: true }),
    request_payer: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
    website_domain: attr.string({ computed: true }),
    website_endpoint: attr.string({ computed: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    cors_rule: block.list({
      attributes: {
        allowed_headers: attr.list({ optional: true }),
        allowed_methods: attr.list({ required: true }),
        allowed_origins: attr.list({ required: true }),
        expose_headers: attr.list({ optional: true }),
        max_age_seconds: attr.number({ optional: true }),
      },
    }),
    grant: block.set({
      attributes: {
        id: attr.string({ optional: true }),
        permissions: attr.set({ required: true }),
        type: attr.string({ required: true }),
        uri: attr.string({ optional: true }),
      },
    }),
    lifecycle_rule: block.list({
      attributes: {
        abort_incomplete_multipart_upload_days: attr.number({ optional: true }),
        enabled: attr.bool({ required: true }),
        id: attr.string({ optional: true, computed: true }),
        prefix: attr.string({ optional: true }),
        tags: attr.map({ optional: true }),
      },
      blocks: {
        expiration: block.single(
          {
            attributes: {
              date: attr.string({ optional: true }),
              days: attr.number({ optional: true }),
              expired_object_delete_marker: attr.bool({ optional: true }),
            },
          },
          { maxItems: 1 },
        ),
        noncurrent_version_expiration: block.single(
          {
            attributes: {
              days: attr.number({ optional: true }),
            },
          },
          { maxItems: 1 },
        ),
        noncurrent_version_transition: block.set({
          attributes: {
            days: attr.number({ optional: true }),
            storage_class: attr.string({ required: true }),
          },
        }),
        transition: block.set({
          attributes: {
            date: attr.string({ optional: true }),
            days: attr.number({ optional: true }),
            storage_class: attr.string({ required: true }),
          },
        }),
      },
    }),
    logging: block.single(
      {
        attributes: {
          target_bucket: attr.string({ required: true }),
          target_prefix: attr.string({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    object_lock_configuration: block.single(
      {
        attributes: {
          object_lock_enabled: attr.string({ optional: true }),
        },
        blocks: {
          rule: block.single(
            {
              attributes: {},
              blocks: {
                default_retention: block.single(
                  {
                    attributes: {
                      days: attr.number({ optional: true }),
                      mode: attr.string({ required: true }),
                      years: attr.number({ optional: true }),
                    },
                  },
                  { minItems: 1, maxItems: 1 },
                ),
              },
            },
            { maxItems: 1 },
          ),
        },
      },
      { maxItems: 1 },
    ),
    replication_configuration: block.single(
      {
        attributes: {
          role: attr.string({ required: true }),
        },
        blocks: {
          rules: block.set(
            {
              attributes: {
                delete_marker_replication_status: attr.string({
                  optional: true,
                }),
                id: attr.string({ optional: true }),
                prefix: attr.string({ optional: true }),
                priority: attr.number({ optional: true }),
                status: attr.string({ required: true }),
              },
              blocks: {
                destination: block.single(
                  {
                    attributes: {
                      account_id: attr.string({ optional: true }),
                      bucket: attr.string({ required: true }),
                      replica_kms_key_id: attr.string({ optional: true }),
                      storage_class: attr.string({ optional: true }),
                    },
                    blocks: {
                      access_control_translation: block.single(
                        {
                          attributes: {
                            owner: attr.string({ required: true }),
                          },
                        },
                        { maxItems: 1 },
                      ),
                      metrics: block.single(
                        {
                          attributes: {
                            minutes: attr.number({ optional: true }),
                            status: attr.string({ optional: true }),
                          },
                        },
                        { maxItems: 1 },
                      ),
                      replication_time: block.single(
                        {
                          attributes: {
                            minutes: attr.number({ optional: true }),
                            status: attr.string({ optional: true }),
                          },
                        },
                        { maxItems: 1 },
                      ),
                    },
                  },
                  { minItems: 1, maxItems: 1 },
                ),
                filter: block.single(
                  {
                    attributes: {
                      prefix: attr.string({ optional: true }),
                      tags: attr.map({ optional: true }),
                    },
                  },
                  { maxItems: 1 },
                ),
                source_selection_criteria: block.single(
                  {
                    attributes: {},
                    blocks: {
                      sse_kms_encrypted_objects: block.single(
                        {
                          attributes: {
                            enabled: attr.bool({ required: true }),
                          },
                        },
                        { maxItems: 1 },
                      ),
                    },
                  },
                  { maxItems: 1 },
                ),
              },
            },
            { minItems: 1 },
          ),
        },
      },
      { maxItems: 1 },
    ),
    server_side_encryption_configuration: block.single(
      {
        attributes: {},
        blocks: {
          rule: block.single(
            {
              attributes: {
                bucket_key_enabled: attr.bool({ optional: true }),
              },
              blocks: {
                apply_server_side_encryption_by_default: block.single(
                  {
                    attributes: {
                      kms_master_key_id: attr.string({ optional: true }),
                      sse_algorithm: attr.string({ required: true }),
                    },
                  },
                  { minItems: 1, maxItems: 1 },
                ),
              },
            },
            { minItems: 1, maxItems: 1 },
          ),
        },
      },
      { maxItems: 1 },
    ),
    timeouts: block.single({
      attributes: {
        create: attr.string({ optional: true }),
        delete: attr.string({ optional: true }),
        read: attr.string({ optional: true }),
        update: attr.string({ optional: true }),
      },
    }),
    versioning: block.single(
      {
        attributes: {
          enabled: attr.bool({ optional: true }),
          mfa_delete: attr.bool({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
    website: block.single(
      {
        attributes: {
          error_document: attr.string({ optional: true }),
          index_document: attr.string({ optional: true }),
          redirect_all_requests_to: attr.string({ optional: true }),
          routing_rules: attr.string({ optional: true }),
        },
      },
      { maxItems: 1 },
    ),
  },
});
