// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, resource } from "../../dsl";
import { COMMON_RESOURCE_ATTRIBUTES, COMMON_RESOURCE_BLOCKS } from "./common";

export const awsSecurityGroupResourceSchema = resource("aws_security_group", {
  attributes: {
    ...COMMON_RESOURCE_ATTRIBUTES,
    arn: attr.string({ computed: true }),
    description: attr.string({ optional: true }),
    id: attr.string({ optional: true, computed: true }),
    name: attr.string({ optional: true, computed: true }),
    name_prefix: attr.string({ optional: true, computed: true }),
    owner_id: attr.string({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    revoke_rules_on_delete: attr.bool({ optional: true }),
    tags: attr.map({ optional: true }),
    tags_all: attr.map({ optional: true, computed: true }),
    vpc_id: attr.string({ optional: true, computed: true }),
  },
  blocks: {
    ...COMMON_RESOURCE_BLOCKS,
    egress: block.set({
      attributes: {
        cidr_blocks: attr.list({ optional: true }),
        description: attr.string({ optional: true }),
        from_port: attr.number({ optional: true }),
        ipv6_cidr_blocks: attr.list({ optional: true }),
        prefix_list_ids: attr.list({ optional: true }),
        protocol: attr.string({ optional: true }),
        security_groups: attr.set({ optional: true }),
        self: attr.bool({ optional: true }),
        to_port: attr.number({ optional: true }),
      },
    }),
    ingress: block.set({
      attributes: {
        cidr_blocks: attr.list({ optional: true }),
        description: attr.string({ optional: true }),
        from_port: attr.number({ optional: true }),
        ipv6_cidr_blocks: attr.list({ optional: true }),
        prefix_list_ids: attr.list({ optional: true }),
        protocol: attr.string({ optional: true }),
        security_groups: attr.set({ optional: true }),
        self: attr.bool({ optional: true }),
        to_port: attr.number({ optional: true }),
      },
    }),
    timeouts: block.single({
      attributes: {
        create: attr.string({ optional: true }),
        delete: attr.string({ optional: true }),
      },
    }),
  },
});
