// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, data } from "../../dsl";

export const awsVpcDataSchema = data("aws_vpc", {
  attributes: {
    arn: attr.string({ computed: true }),
    cidr_block: attr.string({ optional: true, computed: true }),
    default: attr.bool({ optional: true, computed: true }),
    dhcp_options_id: attr.string({ optional: true, computed: true }),
    enable_dns_hostnames: attr.bool({ computed: true }),
    enable_dns_support: attr.bool({ computed: true }),
    enable_network_address_usage_metrics: attr.bool({ computed: true }),
    id: attr.string({ optional: true, computed: true }),
    instance_tenancy: attr.string({ computed: true }),
    ipv6_association_id: attr.string({ computed: true }),
    ipv6_cidr_block: attr.string({ computed: true }),
    main_route_table_id: attr.string({ computed: true }),
    owner_id: attr.string({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    state: attr.string({ optional: true, computed: true }),
    tags: attr.map({ optional: true, computed: true }),
  },
  blocks: {
    cidr_block_associations: block.list({
      attributes: {
        association_id: attr.string({ optional: true }),
        cidr_block: attr.string({ optional: true }),
        state: attr.string({ optional: true }),
      },
    }),
    filter: block.set({
      attributes: {
        name: attr.string({ required: true }),
        values: attr.set({ required: true }),
      },
    }),
    timeouts: block.single({
      attributes: {
        read: attr.string({ optional: true }),
      },
    }),
  },
});
