// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, data } from "../../dsl";

export const awsAvailabilityZonesDataSchema = data("aws_availability_zones", {
  attributes: {
    all_availability_zones: attr.bool({ optional: true }),
    exclude_names: attr.set({ optional: true }),
    exclude_zone_ids: attr.set({ optional: true }),
    group_names: attr.set({ computed: true }),
    id: attr.string({ optional: true, computed: true }),
    names: attr.list({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    state: attr.string({ optional: true }),
    zone_ids: attr.list({ computed: true }),
  },
  blocks: {
    filter: block.set({
      attributes: {
        name: attr.string({ required: true }),
        values: attr.set({ required: true }),
      },
    }),
    timeouts: block.single({
      attributes: {
        read: attr.string({ optional: true }),
      },
    }),
  },
});
