// Generated by scripts/schema-gen/generate-react-hcl-schema.mjs
// DO NOT EDIT MANUALLY.

import { attr, block, data } from "../../dsl";

export const awsAmiDataSchema = data("aws_ami", {
  attributes: {
    allow_unsafe_filter: attr.bool({ optional: true }),
    architecture: attr.string({ computed: true }),
    arn: attr.string({ computed: true }),
    boot_mode: attr.string({ computed: true }),
    creation_date: attr.string({ computed: true }),
    deprecation_time: attr.string({ computed: true }),
    description: attr.string({ computed: true }),
    ena_support: attr.bool({ computed: true }),
    executable_users: attr.list({ optional: true }),
    hypervisor: attr.string({ computed: true }),
    id: attr.string({ optional: true, computed: true }),
    image_id: attr.string({ computed: true }),
    image_location: attr.string({ computed: true }),
    image_owner_alias: attr.string({ computed: true }),
    image_type: attr.string({ computed: true }),
    imds_support: attr.string({ computed: true }),
    include_deprecated: attr.bool({ optional: true }),
    kernel_id: attr.string({ computed: true }),
    last_launched_time: attr.string({ computed: true }),
    most_recent: attr.bool({ optional: true }),
    name: attr.string({ computed: true }),
    name_regex: attr.string({ optional: true }),
    owner_id: attr.string({ computed: true }),
    owners: attr.list({ optional: true }),
    platform: attr.string({ computed: true }),
    platform_details: attr.string({ computed: true }),
    public: attr.bool({ computed: true }),
    ramdisk_id: attr.string({ computed: true }),
    region: attr.string({ optional: true, computed: true }),
    root_device_name: attr.string({ computed: true }),
    root_device_type: attr.string({ computed: true }),
    root_snapshot_id: attr.string({ computed: true }),
    sriov_net_support: attr.string({ computed: true }),
    state: attr.string({ computed: true }),
    state_reason: attr.map({ computed: true }),
    tags: attr.map({ optional: true, computed: true }),
    tpm_support: attr.string({ computed: true }),
    uefi_data: attr.string({ optional: true }),
    usage_operation: attr.string({ computed: true }),
    virtualization_type: attr.string({ computed: true }),
  },
  blocks: {
    block_device_mappings: block.set({
      attributes: {
        device_name: attr.string({ optional: true }),
        ebs: attr.map({ optional: true }),
        no_device: attr.string({ optional: true }),
        virtual_name: attr.string({ optional: true }),
      },
    }),
    filter: block.set({
      attributes: {
        name: attr.string({ required: true }),
        values: attr.set({ required: true }),
      },
    }),
    product_codes: block.set({
      attributes: {
        product_code_id: attr.string({ optional: true }),
        product_code_type: attr.string({ optional: true }),
      },
    }),
    timeouts: block.single({
      attributes: {
        read: attr.string({ optional: true }),
      },
    }),
  },
});
